site_name: iDEC 2025 | OUC-Marine drugs

theme:
  name: material
  logo: img/idec-wiki-logo-white-bg.png
  favicon: img/idec-wiki-logo.png
  custom_dir: overrides  # 用于存放自定义CSS

  palette:
    primary: cyan
    accent: deep purple
    scheme: slate  # 深色模式增强科技感

  features:
    - navigation.sections
    - navigation.instant
    - content.tabs.link

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

extra_css:
  - stylesheets/extra.css  # 自定义科技感和化学感样式

edit_uri: blob/main/docs/
repo_url: https://github.com/idec-teams/2025_OUC-Marine_drugs

copyright: Copyright &copy; 2025 iDEC. CC-BY-4.0 | The International Directed Evolution Competition (iDEC) is a Scottish Charitable Incorporate Organisation (SCIO), registered in Scotland, with charity number：SC050826

nav:
  - Home: index.md
  - Abstract: abstract.md
  - Introduction: introduction.md
  - Results: results.md
  - Materials and Methods: materials_and_methods.md
  - Conclusion: conclusion.md
  - Author Introduction: author_introduction.md
  - Documentation:
      - Protocols: documentation/protocols.md
      - Lab notebook: documentation/notebook.md