site_name: iDEC 2025 | OUC-Marine drugs

theme:
  name: material
  logo: img/idec-wiki-logo-white-bg.png
  favicon: img/idec-wiki-logo.png
  palette:
    primary: blue
    accent: cyan
  features:
    - navigation.expand
    - navigation.top
    # - navigation.tabs  # Uncomment if tab navigation is needed

nav:
  - Home: index.md
  - Project:
      - Abstract: abstract.md
      - Introduction: introduction.md
      - Results: results.md
      - Materials and Methods: materials_and_methods.md
      - Conclusion: conclusion.md
      - References: references.md
      - Author Introduction: author_introduction.md
  - Documentation:
      - Experimental Protocols: documentation/protocols.md
      - Lab Notebook: documentation/notebook.md

plugins:
  - search

extra:
  homepage: https://idec.io